version: '3.8'

services:
  valkey:
    image: valkey/valkey:8.1
    container_name: redbird_valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --appendonly yes --appendfsync everysec
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  valkey_data:
    driver: local 